import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { NextAuthProvider } from "@/providers/auth-provider";
import TokenExpirationHandler from "./components/TokenExpirationHandler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TokenExpirationHandler />
        <NextAuthProvider>{children}</NextAuthProvider>
        <Toaster
          position="top-right"
          toastOptions={{
            success: {
              style: {
                backgroundColor: "#000",
                color: "#fff",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
